version: '3.8'

services:
  ccminer:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: ["-a", "sha256d", "-o", "stratum+tcp://sha256.poolbinance.com:443", "-u", "jotinhacosta", "-p", "x"]
    runtime: nvidia
